name: {{cookiecutter.project_name}} 
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=2.1.5
  - mdanalysis
  - nglview=2.7.7
  - nodejs
  - numpy
  - pandas
  - pip
  - python=3.8.5
  - scipy
  - seaborn
  - tqdm
  - pip:
    - datreant
    - gmxapi==0.2.0a1
    - ipympl
